[package]
name = "jimage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-slice-cast.workspace = true
common.workspace = true
ouroboros.workspace = true
zip.workspace = true
