[package]
name = "jimage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-slice-cast = { workspace = true }
common = { path = "../common" }
ouroboros = "0.15.5"
zip = "0.6.3"