Serial-ATA/sscrt:
  - source: .cargo/config
    template:
      extra_lints: "\"-Aclippy::inline_always\",\n
    \"-Aclippy::new-ret-no-self\",\n
    \"-Aclippy::mut-from-ref\",\n
    \"-Aclippy::used_underscore_binding\",\n
    \"-Aclippy::needless_pass_by_value\",\n
    \"-Aclippy::manual_assert\",\n
    \"-Aclippy::unnecessary_wraps\",\n
    # TODO: Remove this\n
    \"-Aclippy::missing-panics-doc\"\n"