[package]
name = "heap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
classfile = { path = "../classfile" }
class-parser = { path = "../class-parser" }
common = { path = "../common" }