[package]
name = "native_methods"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bitflags.workspace = true
combine.workspace = true
common.workspace = true
walkdir.workspace = true
indexmap.workspace = true