[package]
name = "vm_symbols"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full", "parsing"] }
proc-macro2.workspace = true
quote.workspace = true