[package]
name = "symbols"
version = "0.1.0"
edition = "2021"

[dependencies]
bumpalo = "3.13.0"
common = { path = "../common" }
fxhash = "0.2.1"
indexmap = "1.9.3"
vm_symbols = { path = "../generators/vm_symbols" }