[package]
name = "jimage-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jimage = { path = "../jimage" }
common = { path = "../common" }
byte-slice-cast = "1.2.2"