[workspace]
resolver = "2"
members = [
    "sj",
    "jimage",
    "jmod",
]

[workspace.dependencies]
anyhow = "1.0.93"
clap = "4.0.29"
env_logger = "0.11.5"
libloading = "0.8.5"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"