[package]
name = "jimage_bin"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
class-parser = { path = "../../class-parser" }
jimage = { path = "../../jimage" }
jimage-parser = { path = "../../jimage-parser" }