[package]
name = "jimage_bin"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
classfile = { path = "../../classfile" }
jimage = { path = "../../jimage" }