//! # JNI Functions
//!
//! This module contains the definitions for the JNI functions, divided into modules as is [the specification](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html).

#![allow(unused_variables, non_snake_case)]

use crate::class::ClassPtr;
use crate::heap::reference::ClassRef;

use jni::env::JNIEnv;
use jni::sys::{jclass, JNINativeInterface_};

pub mod array;
pub mod class;
pub mod exceptions;
pub mod field;
pub mod invocation_api;
pub mod method;
pub mod monitor;
pub mod nio;
pub mod object;
pub mod references;
pub mod reflection;
pub mod register;
pub mod string;
pub mod version;
pub mod vm;
pub mod weak;

/// Create a `jclass` from a `ClassRef`
pub fn jclass_from_classref(class: ClassRef) -> jclass {
	ClassRef::into_raw(class) as jclass
}

/// Create a `ClassRef` from a `jclass`
pub unsafe fn classref_from_jclass(class: jclass) -> Option<ClassRef> {
	if class.is_null() {
		return None;
	}

	Some(ClassRef::from_raw(core::mem::transmute::<
		jclass,
		*const ClassPtr,
	>(class)))
}

pub fn new_env() -> JNIEnv {
	let native_interface = JNINativeInterface_ {
		reserved0: core::ptr::null_mut(),
		reserved1: core::ptr::null_mut(),
		reserved2: core::ptr::null_mut(),
		reserved3: core::ptr::null_mut(),

		GetVersion: Some(version::GetVersion),
		DefineClass: Some(class::DefineClass),
		FindClass: Some(class::FindClass),
		FromReflectedMethod: Some(reflection::FromReflectedMethod),
		FromReflectedField: Some(reflection::FromReflectedField),
		ToReflectedMethod: Some(reflection::ToReflectedMethod),
		GetSuperclass: Some(class::GetSuperclass),
		IsAssignableFrom: Some(class::IsAssignableFrom),
		ToReflectedField: Some(reflection::ToReflectedField),
		Throw: Some(exceptions::Throw),
		ThrowNew: Some(exceptions::ThrowNew),
		ExceptionOccurred: Some(exceptions::ExceptionOccurred),
		ExceptionDescribe: Some(exceptions::ExceptionDescribe),
		ExceptionClear: Some(exceptions::ExceptionClear),
		FatalError: Some(exceptions::FatalError),
		PushLocalFrame: Some(references::PushLocalFrame),
		PopLocalFrame: Some(references::PopLocalFrame),
		NewGlobalRef: Some(references::NewGlobalRef),
		DeleteGlobalRef: Some(references::DeleteGlobalRef),
		DeleteLocalRef: Some(references::DeleteLocalRef),
		IsSameObject: Some(object::IsSameObject),
		NewLocalRef: Some(references::NewLocalRef),
		EnsureLocalCapacity: Some(references::EnsureLocalCapacity),
		AllocObject: Some(object::AllocObject),
		NewObject: Some(object::NewObject),
		NewObjectV: Some(object::NewObjectV),
		NewObjectA: Some(object::NewObjectA),
		GetObjectClass: Some(object::GetObjectClass),
		IsInstanceOf: Some(object::IsInstanceOf),
		GetMethodID: Some(method::GetMethodID),
		CallObjectMethod: Some(method::CallObjectMethod),
		CallObjectMethodV: Some(method::CallObjectMethodV),
		CallObjectMethodA: Some(method::CallObjectMethodA),
		CallBooleanMethod: Some(method::CallBooleanMethod),
		CallBooleanMethodV: Some(method::CallBooleanMethodV),
		CallBooleanMethodA: Some(method::CallBooleanMethodA),
		CallByteMethod: Some(method::CallByteMethod),
		CallByteMethodV: Some(method::CallByteMethodV),
		CallByteMethodA: Some(method::CallByteMethodA),
		CallCharMethod: Some(method::CallCharMethod),
		CallCharMethodV: Some(method::CallCharMethodV),
		CallCharMethodA: Some(method::CallCharMethodA),
		CallShortMethod: Some(method::CallShortMethod),
		CallShortMethodV: Some(method::CallShortMethodV),
		CallShortMethodA: Some(method::CallShortMethodA),
		CallIntMethod: Some(method::CallIntMethod),
		CallIntMethodV: Some(method::CallIntMethodV),
		CallIntMethodA: Some(method::CallIntMethodA),
		CallLongMethod: Some(method::CallLongMethod),
		CallLongMethodV: Some(method::CallLongMethodV),
		CallLongMethodA: Some(method::CallLongMethodA),
		CallFloatMethod: Some(method::CallFloatMethod),
		CallFloatMethodV: Some(method::CallFloatMethodV),
		CallFloatMethodA: Some(method::CallFloatMethodA),
		CallDoubleMethod: Some(method::CallDoubleMethod),
		CallDoubleMethodV: Some(method::CallDoubleMethodV),
		CallDoubleMethodA: Some(method::CallDoubleMethodA),
		CallVoidMethod: Some(method::CallVoidMethod),
		CallVoidMethodV: Some(method::CallVoidMethodV),
		CallVoidMethodA: Some(method::CallVoidMethodA),
		CallNonvirtualObjectMethod: Some(method::CallNonvirtualObjectMethod),
		CallNonvirtualObjectMethodV: Some(method::CallNonvirtualObjectMethodV),
		CallNonvirtualObjectMethodA: Some(method::CallNonvirtualObjectMethodA),
		CallNonvirtualBooleanMethod: Some(method::CallNonvirtualBooleanMethod),
		CallNonvirtualBooleanMethodV: Some(method::CallNonvirtualBooleanMethodV),
		CallNonvirtualBooleanMethodA: Some(method::CallNonvirtualBooleanMethodA),
		CallNonvirtualByteMethod: Some(method::CallNonvirtualByteMethod),
		CallNonvirtualByteMethodV: Some(method::CallNonvirtualByteMethodV),
		CallNonvirtualByteMethodA: Some(method::CallNonvirtualByteMethodA),
		CallNonvirtualCharMethod: Some(method::CallNonvirtualCharMethod),
		CallNonvirtualCharMethodV: Some(method::CallNonvirtualCharMethodV),
		CallNonvirtualCharMethodA: Some(method::CallNonvirtualCharMethodA),
		CallNonvirtualShortMethod: Some(method::CallNonvirtualShortMethod),
		CallNonvirtualShortMethodV: Some(method::CallNonvirtualShortMethodV),
		CallNonvirtualShortMethodA: Some(method::CallNonvirtualShortMethodA),
		CallNonvirtualIntMethod: Some(method::CallNonvirtualIntMethod),
		CallNonvirtualIntMethodV: Some(method::CallNonvirtualIntMethodV),
		CallNonvirtualIntMethodA: Some(method::CallNonvirtualIntMethodA),
		CallNonvirtualLongMethod: Some(method::CallNonvirtualLongMethod),
		CallNonvirtualLongMethodV: Some(method::CallNonvirtualLongMethodV),
		CallNonvirtualLongMethodA: Some(method::CallNonvirtualLongMethodA),
		CallNonvirtualFloatMethod: Some(method::CallNonvirtualFloatMethod),
		CallNonvirtualFloatMethodV: Some(method::CallNonvirtualFloatMethodV),
		CallNonvirtualFloatMethodA: Some(method::CallNonvirtualFloatMethodA),
		CallNonvirtualDoubleMethod: Some(method::CallNonvirtualDoubleMethod),
		CallNonvirtualDoubleMethodV: Some(method::CallNonvirtualDoubleMethodV),
		CallNonvirtualDoubleMethodA: Some(method::CallNonvirtualDoubleMethodA),
		CallNonvirtualVoidMethod: Some(method::CallNonvirtualVoidMethod),
		CallNonvirtualVoidMethodV: Some(method::CallNonvirtualVoidMethodV),
		CallNonvirtualVoidMethodA: Some(method::CallNonvirtualVoidMethodA),
		GetFieldID: Some(field::GetFieldID),
		GetObjectField: Some(field::GetObjectField),
		GetBooleanField: Some(field::GetBooleanField),
		GetByteField: Some(field::GetByteField),
		GetCharField: Some(field::GetCharField),
		GetShortField: Some(field::GetShortField),
		GetIntField: Some(field::GetIntField),
		GetLongField: Some(field::GetLongField),
		GetFloatField: Some(field::GetFloatField),
		GetDoubleField: Some(field::GetDoubleField),
		SetObjectField: Some(field::SetObjectField),
		SetBooleanField: Some(field::SetBooleanField),
		SetByteField: Some(field::SetByteField),
		SetCharField: Some(field::SetCharField),
		SetShortField: Some(field::SetShortField),
		SetIntField: Some(field::SetIntField),
		SetLongField: Some(field::SetLongField),
		SetFloatField: Some(field::SetFloatField),
		SetDoubleField: Some(field::SetDoubleField),
		GetStaticMethodID: Some(method::GetStaticMethodID),
		CallStaticObjectMethod: Some(method::CallStaticObjectMethod),
		CallStaticObjectMethodV: Some(method::CallStaticObjectMethodV),
		CallStaticObjectMethodA: Some(method::CallStaticObjectMethodA),
		CallStaticBooleanMethod: Some(method::CallStaticBooleanMethod),
		CallStaticBooleanMethodV: Some(method::CallStaticBooleanMethodV),
		CallStaticBooleanMethodA: Some(method::CallStaticBooleanMethodA),
		CallStaticByteMethod: Some(method::CallStaticByteMethod),
		CallStaticByteMethodV: Some(method::CallStaticByteMethodV),
		CallStaticByteMethodA: Some(method::CallStaticByteMethodA),
		CallStaticCharMethod: Some(method::CallStaticCharMethod),
		CallStaticCharMethodV: Some(method::CallStaticCharMethodV),
		CallStaticCharMethodA: Some(method::CallStaticCharMethodA),
		CallStaticShortMethod: Some(method::CallStaticShortMethod),
		CallStaticShortMethodV: Some(method::CallStaticShortMethodV),
		CallStaticShortMethodA: Some(method::CallStaticShortMethodA),
		CallStaticIntMethod: Some(method::CallStaticIntMethod),
		CallStaticIntMethodV: Some(method::CallStaticIntMethodV),
		CallStaticIntMethodA: Some(method::CallStaticIntMethodA),
		CallStaticLongMethod: Some(method::CallStaticLongMethod),
		CallStaticLongMethodV: Some(method::CallStaticLongMethodV),
		CallStaticLongMethodA: Some(method::CallStaticLongMethodA),
		CallStaticFloatMethod: Some(method::CallStaticFloatMethod),
		CallStaticFloatMethodV: Some(method::CallStaticFloatMethodV),
		CallStaticFloatMethodA: Some(method::CallStaticFloatMethodA),
		CallStaticDoubleMethod: Some(method::CallStaticDoubleMethod),
		CallStaticDoubleMethodV: Some(method::CallStaticDoubleMethodV),
		CallStaticDoubleMethodA: Some(method::CallStaticDoubleMethodA),
		CallStaticVoidMethod: Some(method::CallStaticVoidMethod),
		CallStaticVoidMethodV: Some(method::CallStaticVoidMethodV),
		CallStaticVoidMethodA: Some(method::CallStaticVoidMethodA),
		GetStaticFieldID: Some(field::GetStaticFieldID),
		GetStaticObjectField: Some(field::GetStaticObjectField),
		GetStaticBooleanField: Some(field::GetStaticBooleanField),
		GetStaticByteField: Some(field::GetStaticByteField),
		GetStaticCharField: Some(field::GetStaticCharField),
		GetStaticShortField: Some(field::GetStaticShortField),
		GetStaticIntField: Some(field::GetStaticIntField),
		GetStaticLongField: Some(field::GetStaticLongField),
		GetStaticFloatField: Some(field::GetStaticFloatField),
		GetStaticDoubleField: Some(field::GetStaticDoubleField),
		SetStaticObjectField: Some(field::SetStaticObjectField),
		SetStaticBooleanField: Some(field::SetStaticBooleanField),
		SetStaticByteField: Some(field::SetStaticByteField),
		SetStaticCharField: Some(field::SetStaticCharField),
		SetStaticShortField: Some(field::SetStaticShortField),
		SetStaticIntField: Some(field::SetStaticIntField),
		SetStaticLongField: Some(field::SetStaticLongField),
		SetStaticFloatField: Some(field::SetStaticFloatField),
		SetStaticDoubleField: Some(field::SetStaticDoubleField),
		NewString: Some(string::NewString),
		GetStringLength: Some(string::GetStringLength),
		GetStringChars: Some(string::GetStringChars),
		ReleaseStringChars: Some(string::ReleaseStringChars),
		NewStringUTF: Some(string::NewStringUTF),
		GetStringUTFLength: Some(string::GetStringUTFLength),
		GetStringUTFChars: Some(string::GetStringUTFChars),
		ReleaseStringUTFChars: Some(string::ReleaseStringUTFChars),
		GetArrayLength: Some(array::GetArrayLength),
		NewObjectArray: Some(array::NewObjectArray),
		GetObjectArrayElement: Some(array::GetObjectArrayElement),
		SetObjectArrayElement: Some(array::SetObjectArrayElement),
		NewBooleanArray: Some(array::NewBooleanArray),
		NewByteArray: Some(array::NewByteArray),
		NewCharArray: Some(array::NewCharArray),
		NewShortArray: Some(array::NewShortArray),
		NewIntArray: Some(array::NewIntArray),
		NewLongArray: Some(array::NewLongArray),
		NewFloatArray: Some(array::NewFloatArray),
		NewDoubleArray: Some(array::NewDoubleArray),
		GetBooleanArrayElements: Some(array::GetBooleanArrayElements),
		GetByteArrayElements: Some(array::GetByteArrayElements),
		GetCharArrayElements: Some(array::GetCharArrayElements),
		GetShortArrayElements: Some(array::GetShortArrayElements),
		GetIntArrayElements: Some(array::GetIntArrayElements),
		GetLongArrayElements: Some(array::GetLongArrayElements),
		GetFloatArrayElements: Some(array::GetFloatArrayElements),
		GetDoubleArrayElements: Some(array::GetDoubleArrayElements),
		ReleaseBooleanArrayElements: Some(array::ReleaseBooleanArrayElements),
		ReleaseByteArrayElements: Some(array::ReleaseByteArrayElements),
		ReleaseCharArrayElements: Some(array::ReleaseCharArrayElements),
		ReleaseShortArrayElements: Some(array::ReleaseShortArrayElements),
		ReleaseIntArrayElements: Some(array::ReleaseIntArrayElements),
		ReleaseLongArrayElements: Some(array::ReleaseLongArrayElements),
		ReleaseFloatArrayElements: Some(array::ReleaseFloatArrayElements),
		ReleaseDoubleArrayElements: Some(array::ReleaseDoubleArrayElements),
		GetBooleanArrayRegion: Some(array::GetBooleanArrayRegion),
		GetByteArrayRegion: Some(array::GetByteArrayRegion),
		GetCharArrayRegion: Some(array::GetCharArrayRegion),
		GetShortArrayRegion: Some(array::GetShortArrayRegion),
		GetIntArrayRegion: Some(array::GetIntArrayRegion),
		GetLongArrayRegion: Some(array::GetLongArrayRegion),
		GetFloatArrayRegion: Some(array::GetFloatArrayRegion),
		GetDoubleArrayRegion: Some(array::GetDoubleArrayRegion),
		SetBooleanArrayRegion: Some(array::SetBooleanArrayRegion),
		SetByteArrayRegion: Some(array::SetByteArrayRegion),
		SetCharArrayRegion: Some(array::SetCharArrayRegion),
		SetShortArrayRegion: Some(array::SetShortArrayRegion),
		SetIntArrayRegion: Some(array::SetIntArrayRegion),
		SetLongArrayRegion: Some(array::SetLongArrayRegion),
		SetFloatArrayRegion: Some(array::SetFloatArrayRegion),
		SetDoubleArrayRegion: Some(array::SetDoubleArrayRegion),
		RegisterNatives: Some(register::RegisterNatives),
		UnregisterNatives: Some(register::UnregisterNatives),
		MonitorEnter: Some(monitor::MonitorEnter),
		MonitorExit: Some(monitor::MonitorExit),
		GetJavaVM: Some(vm::GetJavaVM),
		GetStringRegion: Some(string::GetStringRegion),
		GetStringUTFRegion: Some(string::GetStringUTFRegion),
		GetPrimitiveArrayCritical: Some(array::GetPrimitiveArrayCritical),
		ReleasePrimitiveArrayCritical: Some(array::ReleasePrimitiveArrayCritical),
		GetStringCritical: Some(string::GetStringCritical),
		ReleaseStringCritical: Some(string::ReleaseStringCritical),
		NewWeakGlobalRef: Some(weak::NewWeakGlobalRef),
		DeleteWeakGlobalRef: Some(weak::DeleteWeakGlobalRef),
		ExceptionCheck: Some(exceptions::ExceptionCheck),
		NewDirectByteBuffer: Some(nio::NewDirectByteBuffer),
		GetDirectBufferAddress: Some(nio::GetDirectBufferAddress),
		GetDirectBufferCapacity: Some(nio::GetDirectBufferCapacity),
		GetObjectRefType: Some(object::GetObjectRefType),
	};

	let leaked = Box::into_raw(Box::new(native_interface));
	JNIEnv::from(leaked as *mut ::jni::sys::JNIEnv)
}
